import { createSlice } from "@reduxjs/toolkit";
import axios from "axios";

const authSlice = createSlice({
  name: "auth",
  initialState: {
    loading: false,
    user: null,
    error: null,
    message: null,
    isAuthenticated: false,
  },
  reducers: {
    // Added '=>' here
    registerRequest: (state) => {
      state.loading = true;
      state.error = null;
      state.message = null;
    },
    registerSuccess: (state, action) => {
      state.loading = false;
      state.message = action.payload.message;
    },
    // Added '=>' here
    registerFailure: (state, action) => {
      state.loading = false;
      state.error = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { registerRequest, registerSuccess, registerFailure } = authSlice.actions;

export const register = (userData) => async (dispatch) => {
  try {
    dispatch(registerRequest());
    
    // Simplified the promise chain for better readability
    const { data } = await axios.post("/api/auth/register", userData, {
      withCredentials: true,
      headers: {
        "Content-Type": "application/json",
      },
    });

    dispatch(registerSuccess(data));
  } catch (error) {
    dispatch(
      registerFailure(error.response?.data?.message || "Registration failed")
    );
  }
};

export default authSlice.reducer;